class AppConstants {
  static const String appName = 'Student Housing Finder';
  
  static Map<String, Map<String, String>> translations = {
    'en': {
      'app.title': 'Student Housing Finder',
      'app.subtitle': 'Owner Dashboard',
      'home': 'Home',
      'favorites': 'Favorites',
      'messages': 'Messages',
      'profile': 'Profile',
      'search.placeholder': 'Search by location, university...',
      'add.property': 'Add Property',
      'properties.available': 'Properties Available',
      'my.properties': 'My Properties',
      'account.settings': 'Account Settings',
      'language': 'Language',
      'theme': 'Theme',
      'account.details': 'Account Details',
      'logout': 'Logout',
      'edit.profile': 'Edit Profile',
      'name': 'Name',
      'email': 'Email',
      'phone': 'Phone Number',
      'save': 'Save Changes',
      'cancel': 'Cancel',
      'arabic': 'العربية',
      'english': 'English',
      'notifications': 'Notifications',
    },
    'ar': {
      'app.title': 'مكتشف سكن الطلاب',
      'app.subtitle': 'لوحة تحكم المالك',
      'home': 'الرئيسية',
      'favorites': 'المفضلة',
      'messages': 'الرسائل',
      'profile': 'حسابي',
      'search.placeholder': 'ابحث بالموقع، الجامعة...',
      'add.property': 'إضافة عقار',
      'properties.available': 'عقارات متاحة',
      'my.properties': 'عقاراتي',
      'account.settings': 'إعدادات الحساب',
      'language': 'اللغة',
      'theme': 'المظهر',
      'account.details': 'تفاصيل الحساب',
      'logout': 'تسجيل الخروج',
      'edit.profile': 'تعديل الملف الشخصي',
      'name': 'الاسم',
      'email': 'البريد الإلكتروني',
      'phone': 'رقم الهاتف',
      'save': 'حفظ التغييرات',
      'cancel': 'إلغاء',
      'arabic': 'العربية',
      'english': 'English',
      'notifications': 'التنبيهات',
    }
  };
}
