class AppConstants {
  static const String appName = 'Housing Finder';
  
  static Map<String, Map<String, String>> translations = {
    'en': {
      'app.title': 'Housing Finder',
      'app.subtitle': 'Owner Dashboard',
      'home': 'Home',
      'favorites': 'Favorites',
      'messages': 'Messages',
      'profile': 'Profile',
      'search.placeholder': 'Search by location, university...',
      'add.property': 'Add Property',
      'properties.available': 'Properties Available',
      'my.properties': 'My Properties',
      'account.settings': 'Account Settings',
      'language': 'Language',
      'theme': 'Theme',
      'account.details': 'Account Details',
      'logout': 'Logout',
      'edit.profile': 'Edit Profile',
      'name': 'Name',
      'email': 'Email',
      'phone': 'Phone Number',
      'save': 'Save Changes',
      'cancel': 'Cancel',
      'arabic': 'العربية',
      'english': 'English',
      'explore': 'Explore',
      'saved': 'Saved',
      'messages': 'Messages',
      'profile': 'Profile',
      'search.campus': 'Search near your campus...',
      'all.housing': 'All Housing',
      'apartments': 'Apartments',
      'shared': 'Shared',
      'villas': 'Villas',
      'new.listings': 'New Listings',
      'near.mit': 'Near MIT',
      'promo.text': '12 new verified student\nhousings available this\nweek.',
      'verified': 'Verified',
      'free.wifi': 'Free Wifi',
      'gym': 'Gym',
      'laundry': 'Laundry',
      'per.month_short': '/mo',
      'light.mode': 'Light Mode',
      'dark.mode': 'Dark Mode',
      'english.lang': 'English Language',
      'arabic.lang': 'Arabic Language',
      'about.property': 'About the Property',
      'amenities': 'Amenities',
      'location': 'Location',
      'book.viewing': 'Book Viewing',
      'contact.owner': 'Contact Owner',
      'per.month': 'PER MONTH',
      'read.more': 'Read more',
      'read.less': 'Read less',
      'hello': 'Hello',
      'owner.subtitle': 'Manage your property listings and track student interest.',
      'total.properties': 'Total Properties',
      'active.listings': 'Active Listings',
      'total.views': 'Total Views',
      'lifetime': 'Lifetime',
      'active': 'Active',
      '30days': '30 Days',
      'my.properties.title': 'My Properties',
      'add.another': 'Add Another Property',
      'list.next': 'List your next room or apartment',
      'featured': 'FEATURED',
      'notifications': 'Notifications',
      'no.notifications': 'No notifications yet',
      'mark.all.read': 'Mark all as read',
      'login': 'Login',
      'login.subtitle': 'Enter your email and password to access your account.',
      'signup': 'Sign Up',
      'signup.subtitle': 'Create an account to get started',
      'forgot.password': 'Forgot Password?',
      'forgot.password.subtitle': "Enter your email address and we'll send you a link to reset your password.",
      'dont.have.account': "Don't have an account? ",
      'already.have.account': 'Already have an account? ',
      'email.hint': 'Your Email',
      'password.hint': 'Your Password',
      'name.hint': 'Your Name',
      'phone.hint': 'Your Phone Number',
      'university.hint': 'Your University Name',
      'i.am.a': 'I am a',
      'student': 'Student',
      'property.owner': 'Property Owner',
      'send.reset.link': 'Send Reset Link',
      'back.to.login': 'Back to Login',
      'enter.email.pass': 'Please enter email and password',
      'login.failed': 'Login failed',
      'fill.all.fields': 'Please fill in all required fields',
      'account.created': 'Account created successfully! Please login.',
    },
    'ar': {
      'app.title': 'مكتشف السكن',
      'app.subtitle': 'لوحة تحكم المالك',
      'home': 'الرئيسية',
      'favorites': 'المفضلة',
      'messages': 'الرسائل',
      'profile': 'حسابي',
      'search.placeholder': 'ابحث بالموقع، الجامعة...',
      'add.property': 'إضافة عقار',
      'properties.available': 'عقارات متاحة',
      'my.properties': 'عقاراتي',
      'account.settings': 'إعدادات الحساب',
      'language': 'اللغة',
      'theme': 'المظهر',
      'account.details': 'تفاصيل الحساب',
      'logout': 'تسجيل الخروج',
      'edit.profile': 'تعديل الملف الشخصي',
      'name': 'الاسم',
      'email': 'البريد الإلكتروني',
      'phone': 'رقم الهاتف',
      'save': 'حفظ التغييرات',
      'cancel': 'إلغاء',
      'arabic': 'العربية',
      'english': 'English',
      'explore': 'استكشاف',
      'saved': 'المفضلة',
      'messages': 'الرسائل',
      'profile': 'الملف الشخصي',
      'search.campus': 'ابحث بالقرب من جامعتك...',
      'all.housing': 'كل المساكن',
      'apartments': 'شقق',
      'shared': 'سكن مشترك',
      'villas': 'فلل',
      'new.listings': 'إدراجات جديدة',
      'near.mit': 'بالقرب من MIT',
      'promo.text': '12 مسكن جديد تم التحقق منها\nمتاحة هذا الأسبوع.',
      'verified': 'موثق',
      'free.wifi': 'واي فاي مجاني',
      'gym': 'جيم',
      'laundry': 'مغسلة',
      'per.month_short': '/شهرياً',
      'light.mode': 'الوضع الفاتح',
      'dark.mode': 'الوضع الداكن',
      'english.lang': 'اللغة الإنجليزية',
      'arabic.lang': 'اللغة العربية',
      'about.property': 'عن العقار',
      'amenities': 'المرافق',
      'location': 'الموقع',
      'book.viewing': 'حجز معاينة',
      'contact.owner': 'اتصل بالمالك',
      'per.month': 'شهرياً',
      'read.more': 'اقرأ المزيد',
      'read.less': 'عرض أقل',
      'hello': 'مرحباً',
      'owner.subtitle': 'إدارة عقاراتك ومتابعة اهتمامات الطلاب.',
      'total.properties': 'إجمالي العقارات',
      'active.listings': 'العقارات النشطة',
      'total.views': 'إجمالي المشاهدات',
      'lifetime': 'مدى الحياة',
      'active': 'نشط',
      '30days': '30 يوم',
      'my.properties.title': 'عقاراتي',
      'add.another': 'إضافة عقار آخر',
      'list.next': 'أدرج غرفتك أو شقتك التالية',
      'featured': 'مميز',
      'notifications': 'التنبيهات',
      'no.notifications': 'لا توجد تنبيهات بعد',
      'mark.all.read': 'تحديد الكل كمقروء',
      'login': 'تسجيل الدخول',
      'login.subtitle': 'أدخل بريدك الإلكتروني وكلمة المرور للوصول إلى حسابك.',
      'signup': 'إنشاء حساب',
      'signup.subtitle': 'أنشئ حساباً للبدء',
      'forgot.password': 'هل نسيت كلمة المرور؟',
      'forgot.password.subtitle': 'أدخل بريدك الإلكتروني وسنرسل لك رابطاً لإعادة تعيين كلمة المرور.',
      'dont.have.account': 'ليس لديك حساب؟ ',
      'already.have.account': 'لديك حساب بالفعل؟ ',
      'email.hint': 'بريدك الإلكتروني',
      'password.hint': 'كلمة المرور',
      'name.hint': 'اسمك الكامل',
      'phone.hint': 'رقم هاتفك',
      'university.hint': 'اسم جامعتك',
      'i.am.a': 'أنا عبارة عن',
      'student': 'طالب',
      'property.owner': 'صاحب عقار',
      'send.reset.link': 'إرسال رابط البدء',
      'back.to.login': 'العودة لتسجيل الدخول',
      'enter.email.pass': 'يرجى إدخال البريد الإلكتروني وكلمة المرور',
      'login.failed': 'فشل تسجيل الدخول',
      'fill.all.fields': 'يرجى ملء جميع الحقول المطلوبة',
      'account.created': 'تم إنشاء الحساب بنجاح! يرجى تسجيل الدخول.',
    }
  };
}
