class AppConstants {
  static const String appName = 'Housing Finder';
  
  static Map<String, Map<String, String>> translations = {
    'en': {
      'app.title': 'Housing Finder',
      'app.subtitle': 'Owner Dashboard',
      'home': 'Home',
      'favorites': 'Favorites',
      'messages': 'Messages',
      'profile': 'Profile',
      'search.placeholder': 'Search by location, university...',
      'add.property': 'Add Property',
      'properties.available': 'Properties Available',
      'my.properties': 'My Properties',
      'account.settings': 'Account Settings',
      'language': 'Language',
      'theme': 'Theme',
      'account.details': 'Account Details',
      'logout': 'Logout',
      'edit.property': 'Edit Property',
      'images': 'Images',
      'property.status': 'Property Status',
      'available.for.rent': 'Available for Rent',
      'available.now': 'Available Now',
      'fully.furnished': 'Fully Furnished',
      'individual.lease': 'Individual Lease',
      'rented.closed': 'Rented / Closed',
      'currency': 'EGP',
      'update.data': 'Update Property',
      'required': 'Required',
      'wifi': 'WiFi',
      'electricity': 'Electricity Inc.',
      'kitchen': 'Kitchen',
      'cleaning.service': 'Cleaning Service',
      'security': 'Security',
      'min': 'Min',
      'max': 'Max',
      'all': 'All',
      'villa': 'Villa',
      'price.range': 'Price Range',
      'name': 'Name',
      'email': 'Email',
      'phone': 'Phone Number',
      'save': 'Save Changes',
      'cancel': 'Cancel',
      'arabic': 'Arabic',
      'english': 'English',
      'explore': 'Explore',
      'saved': 'Saved',
      'search.campus': 'Search near your campus...',
      'all.housing': 'All Housing',
      'apartments': 'Apartments',
      'shared': 'Shared',
      'villas': 'Villas',
      'new.listings': 'New Listings',
      'near.mit': 'Near MIT',
      'promo.text': '12 new verified student\nhousings available this\nweek.',
      'verified': 'Verified',
      'free.wifi': 'Free Wifi',
      'gym': 'Gym',
      'laundry': 'Laundry',
      'per.month_short': '/mo',
      'light.mode': 'Light Mode',
      'dark.mode': 'Dark Mode',
      'english.lang': 'English Language',
      'arabic.lang': 'Arabic Language',
      'about.property': 'About the Property',
      'amenities': 'Amenities',
      'location': 'Location',
      'book.viewing': 'Book Viewing',
      'contact.owner': 'Contact Owner',
      'contact.me': 'Contact Me',
      'per.month': 'PER MONTH',
      'user': 'User',
      'no.properties.added': 'No properties added yet',
      'error.deleting.property': 'Error deleting property',
      'deleted.success': 'Deleted successfully',
      'read.more': 'Read more',
      'read.less': 'Read less',
      'hello': 'Hello',
      'owner.subtitle': 'Manage your property listings and track student interest.',
      'total.properties': 'Total Properties',
      'active.listings': 'Active Listings',
      'total.views': 'Total Views',
      'lifetime': 'Lifetime',
      'active': 'Active',
      '30days': '30 Days',
      'my.properties.title': 'My Properties',
      'add.another': 'Add Another Property',
      'list.next': 'List your next room or apartment',
      'featured': 'FEATURED',
      'notifications': 'Notifications',
      'no.notifications': 'No notifications yet',
      'mark.all.read': 'Mark all as read',
      'login': 'Login',
      'login.subtitle': 'Enter your email and password to access your account.',
      'signup': 'Sign Up',
      'signup.subtitle': 'Create an account to get started',
      'forgot.password': 'Forgot Password?',
      'forgot.password.subtitle': "Enter your email address and we'll send you a link to reset your password.",
      'dont.have.account': "Don't have an account? ",
      'already.have.account': 'Already have an account? ',
      'email.hint': 'Your Email',
      'password.hint': 'Your Password',
      'name.hint': 'Your Name',
      'phone.hint': 'Your Phone Number',
      'university': 'University',
      'university.name': 'University Name',
      'error.required': 'This field is required',
      'i.am.a': 'I am a',
      'student': 'Student',
      'property.owner': 'Property Owner',
      'send.reset.link': 'Send Reset Link',
      'back.to.login': 'Back to Login',
      'enter.email.pass': 'Please enter email and password',
      'login.failed': 'Login failed',
      'fill.all.fields': 'Please fill in all required fields',
      'account.created': 'Account created successfully! Please login.',
      'filter.results': 'Filter Results',
      'reset': 'Reset',
      'monthly.price': 'Monthly Price',
      'property.type': 'Property Type',
      'rooms': 'Rooms',
      'any': 'Any',
      'apply.filters': 'Apply Filters',
      'appearance': 'Appearance',
      'general.settings': 'General Settings',
      'account': 'Account',
      'onboarding.title1': 'Find Your Ideal Home',
      'onboarding.subtitle1': 'Browse thousands of student-friendly\nproperties near your university',
      'onboarding.title2': 'Easy Communication',
      'onboarding.subtitle2': 'Connect directly with property owners via\nchat, call, or WhatsApp',
      'onboarding.title3': 'List Your Property',
      'onboarding.subtitle3': 'Property owners can easily list and manage\ntheir rentals',
      'skip': 'Skip',
      'next': 'Next',
      'get.started': 'Get Started',
      'views': 'Views',
      'owner': 'Owner',
      'description': 'Description',
      'personal.info': 'Personal Info',
      'my.reviews': 'My Reviews',
      'settings': 'Settings',
      'help.center': 'Help Center',
      'enabled': 'Enabled',
      'disabled': 'Disabled',
      'faq': 'Frequently Asked Questions',
      'faq.desc': 'Find answers to common questions about booking and hosting.',
      'contact.support': 'Contact Support',
      'contact.support.desc': 'Our team is here to help you 24/7.',
      'privacy.policy': 'Privacy Policy',
      'privacy.policy.desc': 'Read how we handle your data.',
      'terms.service': 'Terms of Service',
      'terms.service.desc': 'Rules and guidelines for using our platform.',
      'profile.picture.updated': 'Profile picture updated! ✅',
      'upload.failed': 'Upload failed: ',
      'delete.chat.title': 'Delete Chat?',
      'delete.chat.confirm': 'Are you sure you want to delete this conversation?',
      'search': 'Search...',
      'no.conversations': 'No conversations yet.',
      'delete': 'Delete',
      'delete.all': 'Delete All',
      'delete.all.title': 'Delete All Notifications?',
      'delete.all.confirm': 'Are you sure you want to delete all your notifications?',
      'error.deleting': 'Error deleting: ',
      'property.updated': 'Property updated!',
      'at.least.one.image': 'Please keep at least one image',
      'error': 'Error: ',
      'image.load.failed': 'Failed to load image',
      'error.loading.properties': 'Error loading properties: ',
      'delete.property.title': 'Delete Property',
      'delete.property.confirm': 'Are you sure you want to delete this listing?',
      'no.properties.listed': 'No properties listed yet.',
      'add.property.title': 'Add New Property',
      'property.photos': 'Property Photos',
      'add.photos': 'Add Photos',
      'basic.info': 'Basic Information',
      'property.title': 'Property Title',
      'property.category': 'Property Category',
      'price': 'Price',
      'amenities.features': 'Amenities & Features',
      'publish.now': 'Publish Property Now',
      'at.least.one.photo': 'Please add at least one image',
      'published.success': 'Property published successfully! 🚀',
      'apartment': 'Apartment',
      'studio': 'Studio',
      'shared.room': 'Shared Room',
      'reception': 'Reception',
      'salon': 'Salon',
      'rooms.count': 'Rooms Count',
      'furnishing': 'Furnishing Status',
      'furnished': 'Furnished',
      'unfurnished': 'Unfurnished',
      'fridge': 'Fridge',
      'washing.machine': 'Washing Machine',
      'tv': 'TV / Screen',
      'ac': 'Air Conditioning (AC)',
      'water.heater': 'Water Heater',
      'study.desk': 'Study Desk',
      'beds.count': 'Beds Count',
      'beds': 'Beds',
      'other': 'Other',
      'whatsapp': 'WhatsApp',
      'call': 'Call',
      'you': 'You',
      'available': 'Available',
      'rented': 'Rented',
      'stats': 'Statistics',
      'avg.price': 'Avg Price',
      'other.features': 'Other Features',
      'added.to.favorites': 'Added to favorites',
      'removed.from.favorites': 'Removed from favorites',
      'phone.not.available': 'Owner phone not available',
      'interest.message': 'Hello, I am interested in your property:',
      'error.launch.whatsapp': 'Could not launch WhatsApp',
    },
    'ar': {
      'app.title': 'مكتشف السكن',
      'app.subtitle': 'لوحة تحكم المالك',
      'home': 'الرئيسية',
      'favorites': 'المفضلة',
      'messages': 'الرسائل',
      'profile': 'حسابي',
      'search.placeholder': 'ابحث بالموقع، الجامعة...',
      'add.property': 'إضافة عقار',
      'properties.available': 'عقارات متاحة',
      'my.properties': 'عقاراتي',
      'account.settings': 'إعدادات الحساب',
      'language': 'اللغة',
      'theme': 'المظهر',
      'account.details': 'تفاصيل الحساب',
      'logout': 'تسجيل الخروج',
      'edit.property': 'تعديل العقار',
      'images': 'الصور',
      'property.status': 'حالة العقار',
      'available.for.rent': 'متاح للإيجار',
      'available.now': 'متاح الآن',
      'fully.furnished': 'مفروش بالكامل',
      'individual.lease': 'عقد فردي',
      'rented.closed': 'تم التأجير / مغلق',
      'currency': 'ج.م',
      'update.data': 'تحديث البيانات',
      'required': 'مطلوب',
      'wifi': 'واي فاي',
      'electricity': 'الكهرباء شاملة',
      'kitchen': 'مطبخ',
      'cleaning.service': 'خدمة تنظيف',
      'security': 'أمن',
      'min': 'الأدنى',
      'max': 'الأعلى',
      'all': 'الكل',
      'villa': 'فيلا',
      'price.range': 'نطاق السعر',
      'name': 'الاسم',
      'email': 'البريد الإلكتروني',
      'phone': 'رقم الهاتف',
      'save': 'حفظ التغييرات',
      'cancel': 'إلغاء',
      'arabic': 'العربية',
      'english': 'English',
      'explore': 'استكشاف',
      'saved': 'المفضلة',
      'search.campus': 'ابحث بالقرب من جامعتك...',
      'all.housing': 'كل المساكن',
      'apartments': 'شقق',
      'shared': 'سكن مشترك',
      'villas': 'فلل',
      'new.listings': 'إدراجات جديدة',
      'near.mit': 'بالقرب من MIT',
      'promo.text': '12 مسكن جديد تم التحقق منها\nمتاحة هذا الأسبوع.',
      'verified': 'موثق',
      'free.wifi': 'واي فاي مجاني',
      'gym': 'جيم',
      'laundry': 'مغسلة',
      'per.month_short': '/شهرياً',
      'light.mode': 'الوضع الفاتح',
      'dark.mode': 'الوضع الداكن',
      'english.lang': 'اللغة الإنجليزية',
      'arabic.lang': 'اللغة العربية',
      'about.property': 'عن العقار',
      'amenities': 'المرافق',
      'location': 'الموقع',
      'book.viewing': 'حجز معاينة',
      'contact.owner': 'اتصل بالمالك',
      'contact.me': 'تواصل معي',
      'per.month': 'شهرياً',
      'user': 'مستخدم',
      'no.properties.added': 'لا توجد عقارات مضافة',
      'error.deleting.property': 'حدث خطأ أثناء الحذف',
      'deleted.success': 'تم الحذف بنجاح',
      'read.more': 'اقرأ المزيد',
      'read.less': 'عرض أقل',
      'hello': 'مرحباً',
      'owner.subtitle': 'إدارة عقاراتك ومتابعة اهتمامات الطلاب.',
      'total.properties': 'إجمالي العقارات',
      'active.listings': 'العقارات النشطة',
      'total.views': 'إجمالي المشاهدات',
      'lifetime': 'مدى الحياة',
      'active': 'نشط',
      '30days': '30 يوم',
      'my.properties.title': 'عقاراتي',
      'add.another': 'إضافة عقار آخر',
      'list.next': 'أدرج غرفتك أو شقتك التالية',
      'featured': 'مميز',
      'notifications': 'التنبيهات',
      'no.notifications': 'لا توجد تنبيهات بعد',
      'mark.all.read': 'تحديد الكل كمقروء',
      'login': 'تسجيل الدخول',
      'login.subtitle': 'أدخل بريدك الإلكتروني وكلمة المرور للوصول إلى حسابك.',
      'signup': 'إنشاء حساب',
      'signup.subtitle': 'أنشئ حساباً للبدء',
      'forgot.password': 'هل نسيت كلمة المرور؟',
      'forgot.password.subtitle': 'أدخل بريدك الإلكتروني وسنرسل لك رابطاً لإعادة تعيين كلمة المرور.',
      'dont.have.account': 'ليس لديك حساب؟ ',
      'already.have.account': 'لديك حساب بالفعل؟ ',
      'email.hint': 'بريدك الإلكتروني',
      'password.hint': 'كلمة المرور',
      'name.hint': 'اسمك الكامل',
      'phone.hint': 'رقم هاتفك',
      'university': 'الجامعة',
      'university.name': 'اسم الجامعة',
      'error.required': 'هذا الحقل مطلوب',
      'i.am.a': 'أنا عبارة عن',
      'student': 'طالب',
      'property.owner': 'صاحب عقار',
      'send.reset.link': 'إرسال رابط البدء',
      'back.to.login': 'العودة لتسجيل الدخول',
      'enter.email.pass': 'يرجى إدخال البريد الإلكتروني وكلمة المرور',
      'login.failed': 'فشل تسجيل الدخول',
      'fill.all.fields': 'يرجى ملء جميع الحقول المطلوبة',
      'account.created': 'تم إنشاء الحساب بنجاح! يرجى تسجيل الدخول.',
      'filter.results': 'نتائج التصفية',
      'reset': 'إعادة ضبط',
      'monthly.price': 'السعر الشهري',
      'property.type': 'نوع العقار',
      'rooms': 'غرف',
      'any': 'أي',
      'apply.filters': 'تطبيق الفلاتر',
      'appearance': 'المظهر',
      'general.settings': 'إعدادات عامة',
      'account': 'الحساب',
      'onboarding.title1': 'ابحث عن منزلك المثالي',
      'onboarding.subtitle1': 'تصفح آلاف العقارات المناسبة للطلاب بالقرب من جامعتك',
      'onboarding.title2': 'تواصل سهل وسريع',
      'onboarding.subtitle2': 'تواصل مباشرة مع أصحاب العقارات عبر الدردشة أو الاتصال',
      'onboarding.title3': 'أضف عقارك الخاص',
      'onboarding.subtitle3': 'يمكن لأصحاب العقارات إدراج وإدارة عقاراتهم للإيجار بسهولة',
      'skip': 'تخطي',
      'next': 'التالي',
      'get.started': 'ابدأ الآن',
      'views': 'مشاهدة',
      'owner': 'المالك',
      'description': 'الوصف',
      'personal.info': 'المعلومات الشخصية',
      'my.reviews': 'تقييماتي',
      'settings': 'الإعدادات',
      'help.center': 'مركز المساعدة',
      'enabled': 'مفعل',
      'disabled': 'معطل',
      'faq': 'الأسئلة الشائعة',
      'faq.desc': 'ابحث عن إجابات للأسئلة الشائعة حول الحجز والاستضافة.',
      'contact.support': 'اتصل بالدعم',
      'contact.support.desc': 'فريقنا هنا لمساعدتك على مدار الساعة.',
      'privacy.policy': 'سياسة الخصوصية',
      'privacy.policy.desc': 'اقرأ كيف نتعامل مع بياناتك.',
      'terms.service': 'شروط الخدمة',
      'terms.service.desc': 'القواعد والإرشادات لاستخدام منصتنا.',
      'profile.picture.updated': 'تم تحديث الصورة الشخصية! ✅',
      'upload.failed': 'فشل التحميل: ',
      'delete.chat.title': 'حذف المحادثة؟',
      'delete.chat.confirm': 'هل أنت متأكد من حذف هذه المحادثة؟',
      'search': 'بحث...',
      'no.conversations': 'لا توجد محادثات بعد',
      'delete': 'حذف',
      'delete.all': 'حذف الكل',
      'delete.all.title': 'حذف جميع التنبيهات؟',
      'delete.all.confirm': 'هل أنت متأكد من رغبتك في حذف جميع التنبيهات الخاصة بك؟',
      'error.deleting': 'خطأ في الحذف: ',
      'property.updated': 'تم تحديث العقار!',
      'at.least.one.image': 'يرجى الإبقاء على صورة واحدة على الأقل',
      'error': 'خطأ: ',
      'image.load.failed': 'عذراً، تعذر تحميل الصورة',
      'error.loading.properties': 'خطأ في تحميل العقارات: ',
      'delete.property.title': 'حذف العقار',
      'delete.property.confirm': 'هل أنت متأكد من حذف هذا العقار؟',
      'no.properties.listed': 'لا يوجد عقارات مدرجة بعد.',
      'add.property.title': 'إضافة عقار جديد',
      'property.photos': 'صور العقار',
      'add.photos': 'إضافة صور',
      'basic.info': 'المعلومات الأساسية',
      'property.title': 'عنوان العقار',
      'property.category': 'فئة السكن',
      'price': 'السعر',
      'amenities.features': 'المرافق والخدمات',
      'publish.now': 'نشر العقار الآن',
      'at.least.one.photo': 'يرجى إضافة صورة واحدة على الأقل',
      'published.success': 'تم نشر العقار بنجاح! 🚀',
      'apartment': 'شقة',
      'studio': 'استوديو',
      'shared.room': 'غرفة مشتركة',
      'furnished': 'مفروش',
      'unfurnished': 'غير مفروش',
      'fridge': 'ثلاجة',
      'washing.machine': 'غسالة',
      'tv': 'شاشة / تلفاز',
      'ac': 'تكييف',
      'water.heater': 'سخان مياه',
      'study.desk': 'مكتب دراسة',
      'beds.count': 'عدد الأسرة',
      'beds': 'سرير',
      'other': 'أخرى',
      'whatsapp': 'واتساب',
      'call': 'اتصال',
      'reception': 'ريسبشن',
      'salon': 'صالون',
      'stats': 'الإحصائيات',
      'avg.price': 'متوسط السعر',
      'other.features': 'مميزات إضافية',
      'rooms.count': 'عدد الغرف',
      'you': 'أنت',
      'available': 'متاح',
      'rented': 'تم التأجير',
      'added.to.favorites': 'تمت الإضافة للمفضلة',
      'removed.from.favorites': 'تمت الإزالة من المفضلة',
      'phone.not.available': 'رقم المالك غير متاح',
      'interest.message': 'مرحباً، أنا مهتم بعقارك:',
      'error.launch.whatsapp': 'تعذر فتح واتساب',
    },
  };
}
